language: python
cache: pip

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  matrix:
    - DJANGO=1.7.8 DB=sqlite
    - DJANGO=1.8.12 DB=sqlite
    - DJANGO=1.9.5 DB=sqlite
    - DJANGO=1.10 DB=sqlite
    - DJANGO=1.11 DB=sqlite
    - DJANGO=2.0 DB=sqlite

matrix:
  allow-failures:
  exclude:
    - python: '2.7'
      env: DJANGO=2.0 DB=sqlite

# command to install dependencies
install:
  - pip install .
  - pip install -q Django==$DJANGO
  - pip install -r test_requirements.txt

# command to run tests
script: python manage.py test
